title: Human Boring
description: Thoughts from a boring person
baseurl:
url: https://humanboring.github.io
repository: https://github.com/humanboring/humanboring.github.io/
locale: "en-gb"
twitter_username: humanboring



# Build settings
markdown: kramdown
remote_theme: humanboring/humanboring_theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
exclude:
  - Gemfile
  - Gemfile.lock
  - s3_website.yml
  - deploy.sh
